Repository ostis-ai/sc-web, pull requests merged in 2023-01, with the labels that each got.

#58 docs: fix README installation section
  README.md
Labels: bug, documentation, 0.7.1

#51 Improve sc2scs component, remove html updating
  client/js/Core/componentsandbox.js
  client/js/Core/main.js
  client/js/Core/server.js
  client/js/Core/translation.js
  client/js/Ui/locker.js
  client/js/Ui/windowmanager.js
  components/scs/src/scn-component.js
  components/scs/src/scn-output.js
  components/scs/src/scn-tree.js
  components/scs/src/scs-viewer.js
  package-lock.json
  package.json
  server/handlers/api.py
  server/keynodes.py
Labels: enhancement, 0.7.1, scn-component

#46 feat: remove a button
  client/templates/base.html
  docs/changelog.md
Labels: enhancement, 0.7.1

#53 Pointer cursor when hovering over expert mode switch label
  client/static/components/css/common.css
  docs/changelog.md
Labels: 0.7.1, expert mode

#61 Add double click logic in scg view
  client/js/Core/main.js
  client/js/Ui/menu.js
  client/js/Ui/windowmanager.js
  client/js/Utils/sc_helper.js
  components/scg/src/listener/scg-mode-select.js
  components/scg/src/scg-render.js
  components/scs/src/scn-component.js
  docs/changelog.md
Labels: 0.8.0
